### ISSUE TITLE
There is a possibility of attack through the attributes on*

### ISSUE THREAD

**Issue by web36m** [ericnorris/striptags#13]
This code is possible to execute    

``` javascript
striptags('<a onclick="alert(\'Alert!!!\');">The link</a>', '<a>');
```

(edited)

**Comment by ericnorris** [comment]
Hey @web36m, thanks for your interest! I ran your code verbatim and got an error, output is below:

```
> striptags('<a onclick="alert('Alert!!!');">The link</a>', '<a>');
SyntaxError: missing ) after argument list
    at Object.exports.createScript (vm.js:24:10)
    at REPLServer.defaultEval (repl.js:225:25)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:417:12)
    at emitOne (events.js:95:20)
    at REPLServer.emit (events.js:182:7)
    at REPLServer.Interface._onLine (readline.js:211:10)
    at REPLServer.Interface._line (readline.js:550:8)
    at REPLServer.Interface._ttyWrite (readline.js:827:14)
```

After fixing the issue (it appears you didn't escape the single quotes), it does in fact let the `<a>` tag and its attributes through - because you specified `<a>` as an allowable tag.

Per the [readme](https://github.com/ericnorris/striptags/blob/master/README.md):

> Here is a [great StackOverflow answer](http://stackoverflow.com/a/5793453) regarding how strip_tags (**when used without specifying allowableTags**) is not vulnerable to scripting attacks.

This is a library for stripping HTML tags, not sanitizing them. You may need to look into something else (maybe a server-side sanitization library like [HTML Purifier](http://htmlpurifier.org/)).

**Comment by web36m** [comment]
Has been edited first

**Comment by ericnorris** [comment]
@web36m, I see that you updated the code, thanks! The last point in my comment still stands - if you use allowable tags you are vulnerable to scripting attacks, as you have shown. This is something that I mention in the readme.

I am going to close this issue, but thanks again.
