### ISSUE TITLE
v2.2.0 with breaking changes

### ISSUE THREAD

**Issue by DudaGod** [ericnorris/striptags#21]
Hello.
Today you published new version 2.2.0 which works only in nodejs v6 and upper.
https://github.com/ericnorris/striptags/blob/v2.2.0/striptags.js#L24

In our team we still have projects on nodejs v4 and this changes break everything. Please revert this major version or write in README that you support only nodejs v6 and upper.

Thank you.

**Comment by wallali** [comment]
Having same issue as @DudaGod. striptags no longer works with nodejs v4.

`function striptags(html = '', allowableTags = [], tagReplacement = '') {`
`SyntaxError: Unexpected token =`

This change is not backwards compatible with node js v4 and should perhaps be a major version update to striptags i.e. v3.0.0 due to its breaking nature or should be reverted.

**Comment by designeng** [comment]
+1

**Comment by gregorybesson** [comment]
+1

**Comment by ilyasgaraev** [comment]
+1 (nodejs v6.2.2)

**Comment by ghost** [comment]
+1

**Comment by ericnorris** [comment]
For the time being I reverted the change and pushed an updated version (`v2.2.1`) to GitHub and NPM. Please refrain from +1 style comments, as GitHub has added "reactions" for you to use in order to echo someone's sentiment.

Apologies for the disruption! I'll save a modernization of the library for a `v3.0.0` release.

@DudaGod, feel free to reopen if this didn't fix the problem for you.

**Comment by gregorybesson** [comment]
Thank you so much Eric. You've been fast :)

I think using "+1" in this typical case : A dangerous BC break is ok as it will be displayed on screen and easy to see. It's like a "manual emergency signal".

It was not intended to be seen as an insult or a violent claim and mentions are not visible enough in this case.

Once again. Thank you for your great work. You make many people happy !
