### ISSUE TITLE
[Proposal] Black list of tags

### ISSUE THREAD

**Issue by AlexMiroshnikov** [ericnorris/striptags#32]
As far as I understand, currently it's possible to pass as the 2nd argument a white list of tags, and in such case those tags will not be removed from original html.
@ericnorris What about adding a feature allowing to pass black list as well? E.g.,
`striptags(html, ['!p'])`
could leave all the tags except `<p>`.
If you're interested, I'm ready to handle this task.

**Comment by ericnorris** [comment]
I commented in #33, but I'll comment here as well: my goal is to keep this library as simple as possible, and avoid straying too far from the original spec. I appreciate your input though!

**Comment by SystemDisc** [comment]
Allowing blacklisting would be amazing. Please reconsider.

**Comment by ewrogers** [comment]
Jumping in this discussion to provide another perspective on why this feature would be useful:

I currently use this library to strip out tags from HTML-based email and then scrape out information via RegExp. I have to be able to present the stripped email documents in a UI so the user can see where the scraped information came from.

The problem I run into is that there are malformed tags, typically email address related that get stripped out. For example `<blahblah@blah.com <mailto:blahblah@blahblah.com>>` where the 'tag' type itself is being seen as a "blahblah@blah.com" tag which is invalid and there's no way to really whitelist this reliably. Email addresses are one aspect that I must scrape.

I think a good approach would be to have a filter callback function you could provide to do the whitelist/blacklisting yourself... or at least let me detect these cases and pass them through as not to be stripped.

My current workaround is to do some pre-processing of emails that fall into this pattern (RegExp replace) but it's hack a best.

**Comment by AlexMiroshnikov** [comment]
@ewrogers 
>I think a good approach would be to have a filter callback function you could provide to do the whitelist/blacklisting yourself

Could you please provide a sample of input, call and expected output for this case? Just a minimalistic one, so everyone could get the idea better :) .

**Comment by ewrogers** [comment]
Sure, after digging further this week I have the case of XML tags getting stripped when I still want them to be preserved but I do want certain HTML tags stripped.

Basically, if `tag_replacement` could be an optional function like so:
```
// name = name of the tag (such as 'a', 'img', 'b')
// content = content within the tag (such as 'href = ...')

(name, content) => {
    // Return a string to replace, return null to keep as-is
    return name === 'script' ? 'REDACTED' : null
}
```

**Comment by ericnorris** [comment]
@ewrogers it's hard for me to recommend specifics without knowing the full details of your workflow, but it seems to me that regexes + striptags might not be the best answer for that kind of processing. Have you considered exploring a [BeautifulSoup](https://www.crummy.com/software/BeautifulSoup/)-like library? I'm sure there must be some analog in NodeJS.

Having a callback function for each tag makes this library into something more akin to a SAX parser, which I'd like to avoid. If you're doing heavier processing, then you'll want something more heavyweight.

I'm still somewhat open to the idea, but I'm trying to err on the side of less is more.

**Comment by ewrogers** [comment]
I know my case might be specific, but I think there is definitely the problem of XML (or other similar formats) being a casualty of stripping HTML tags.

If I was scraping HTML documents, then I'd say BeautifulSoup would be apt. However, I'm simply using striptags to sanitize the data as a textual representation.

From an abstract view, why should striptags assume any data between carets `<>` is automatically a tag? Sure, that may work for some, but more advanced control would be desirable.

**Comment by ericnorris** [comment]
@ewrogers, gotcha. I feel that you probably shouldn't be using `striptags` for anything but the simplest of HTML+XML scraping tasks.

`BeautifulSoup` works for both HTML and XML, so it should be equally applicable in your case (I assume, ignoring the fact I don't have specifics).

`striptags` assumes anything within carets `<>` is a tag because, well, that's the definition of a tag. It expects HTML, and per the W3 doc (https://www.w3.org/TR/html5/syntax.html#start-tags):

> Start tags must have the following format:
> 
> The first character of a start tag must be a "<" (U+003C) character.
> The next few characters of a start tag must be the element's tag name.

At the very minimum `striptags` is meant for a straightforward way of sanitizing user input - if you call `striptags(unsafe_html)`, the result will be safe HTML. I'd like to stay as close to that as possible.

**Comment by SystemDisc** [comment]
Following W3 docs strictly is dangerous if the expectation is to filter out unsafe HTML for browsers - browsers render tags that aren't technically formatted correctly under many odd scenarios.

**Comment by ericnorris** [comment]
@SystemDisc thanks for the feedback. Unless I am mistaken, no browsers consider
```
< something >
``` 
a tag because it isn't one, by definition. While you are right that browsers do a lot of things to handle malformed HTML, they tend to be around handling "tag soup", not malformed tags. I've tested this in a couple browsers to double-check.

With that in mind, and [per the explanation linked in the README]( https://stackoverflow.com/questions/5788527/is-strip-tags-vulnerable-to-scripting-attacks/5793453#5793453), `striptags` is safe. Note that PHP's `strip_tags` operates the same way, and we would very likely hear about it if that was vulnerable.

**Comment by SystemDisc** [comment]
Understood - I just wanted to point out that browsers render HTML which may not match specifications exactly. `< tag >` is not one of those scenarios.

**Comment by PierBover** [comment]
It is really counterintuitive that `striptags` would strip all tags by default.

I would expect the library to strip the tags that have to be removed, instead of defining the ones that don't have to be stripped.

While I understand the reluctance to change the default behavior, an option to keep all tags by default and only strip the defined ones would be very helpful for newsletters and such.

**Comment by dinbrca** [comment]
Just for people reference - List of HTML tags as array:
https://github.com/sindresorhus/html-tags/blob/master/html-tags.json

**Comment by kuoruan** [comment]
Allow to pass a function is a better choice.

```
striptags(html, function (tag) {
    return is_tag_allowed;
})
```

**Comment by i-break-codes** [comment]
This is a no-nonsense feature request. It's way easier for me to add a list of tags I would like to remove vs what I would like to keep.

**Comment by ericnorris** [comment]
Hey all! Spurred by a recent pull request to add linting, I decided to take a fresh look at the library and took a chance at rewriting it in Typescript.

In doing so I thought about this open issue - my biggest concern was (and still is) that a "disallow list" might provide the illusion of safety, e.g. someone may disallow `script` tags and think they are safe from XSS. I've decided to describe this concern in the "Safety" section of the README, and allow developers to decide if this is the correct behavior for their use case. You can now pass in `disallowedTags` in the options argument.
