### ISSUE TITLE
Strip only <img> tag

### ISSUE THREAD

**Issue by rajkuttie** [ericnorris/striptags#34]
I had a requirement of Remove only image tag on collection of some html. 
My Code : 

`  var html = result7[i].post.properties.context;
        var tem = striptags(html, '<img>');`

Before this code is working perfect  . Our project is goes to production. But now This code is not woking. I can't remove Image tag . Documentation also updated .    Why this Module not working now ? I want explanation . and I want solution . ? How I can remove Img tag ?

**Comment by ericnorris** [comment]
Hey @rajkuttie, thanks for the report. `striptags` has never offered the ability to only remove one tag; it only allows for specifying tags *not* to remove. By default it removes *all* tags unless specified otherwise. This hasn't changed in any way that I am aware of.

Do you mind providing a little more information to help debug your issue?

**Comment by rajkuttie** [comment]
Thank you for your response . I understand your situation. Now I have Collection of HTML content .  My requirement is remove only Image Tag only . Is it possible for this module ?

**Comment by ericnorris** [comment]
At the moment, no. There is issue #32 which proposes a tag blacklist, but that is not currently implemented in this module. I'll go ahead and close this issue for now, feel free to follow the other issue if you are interested or look for a different solution.

**Comment by AlexMiroshnikov** [comment]
@rajkuttie Feel free to grab a fork https://github.com/AlexMiroshnikov/striptags . Usage described at https://github.com/ericnorris/striptags/pull/33 .

**Comment by rajkuttie** [comment]
@AlexMiroshnikov I will try
