### ISSUE TITLE
Avoid stripping `<http://uppy.io>`

### ISSUE THREAD

**Issue by kvz** [ericnorris/striptags#45]
Hi, thanks for striptags! 

I have some markdown that I want to strip from `<div>`s and thought to use striptags on it. However it also contains links such as `<https://uppy.io>` which isn't an HTML tag, and which is valid markdown. I have a bunch more of these types of links, and I can't predict the addresses upfront.

How would I go about whitelisting this type of tag?

**Comment by ericnorris** [comment]
Hey @kvz!

`striptags` won't fit the bill in this case, since you can't give it a predetermined list of tags to allow. You would need to HTML encode those links before passing them in or use the standard markdown link format (i.e. `[link text](url)`). Maybe a regular expression would be safe to use for at least converting the links?

**Comment by kvz** [comment]
Hi! Thanks for the suggestion, I managed to make it work that way. That said, maybe the striptags algorithm could be made to be more discriminatory? Like, an opening tagname (part before white space) can’t have a /. That would avoid overeagerly deleting markdown that could never have been html anyway(?)

**Comment by ericnorris** [comment]
Glad you got something working. For the purposes of stripping tags I have been erring on the side of caution, i.e. < should _never_ appear in un-encoded strings. I'd rather stick with that than make exceptions, but thank you for the suggestion.
