### ISSUE TITLE
striptags does not allow < symbol

### ISSUE THREAD

**Issue by agrishkan** [ericnorris/striptags#49]
To reproduce:
```
var striptags = require('striptags');
var r = striptags("<div>Result is <35 widgets</div>")
```

Expected output: `Result is <35 widgets`
Actual output: `Result is `

**Comment by ericnorris** [comment]
Hey @agrishkan! This is actually expected behavior. The `<35` in your example is malformed - `<` should be properly HTML encoded as `&lt;` if it is not a tag element.

`striptags` is a state machine that will strip any `<` or `>` in the text, regardless of whether or not it was meant to be a tag or not.

**Comment by Strate** [comment]
Fix is here: https://github.com/megaplan/striptags/commit/9cc17473d22beef81ebc38e9ab15984bfa6f2e3c

**Comment by Strate** [comment]
@ericnorris btw, php's `strip_tags` function handles this situation correctly:
```
% php -a
Interactive mode enabled

php > var_dump(strip_tags('<div>result < 35</div>'));
string(11) "result < 35"
```

**Comment by ericnorris** [comment]
Hey @Strate! The example you gave is slightly different from the example in the issue, and both `striptags` and PHP's `strip_tags` have the same behavior.

this library:
```js
console.log(striptags('<div>result < 35</div>'))
```

output: `result < 35`

PHP ([source](https://3v4l.org/VmcTL)):
```php
<?php

echo strip_tags('<div>result < 35</div>') . "\n";
```

output: `result < 35`

Now let's look at the issue's example in PHP ([source](https://3v4l.org/R7i82)):

```php
<?php

echo strip_tags("<div>Result is <35 widgets</div>") . "\n";
```

output: `Result is `

Same as the `striptags` library. Any `<` followed by non-whitespace is stripped out as it could be considered an HTML tag, and thus unsafe. Honestly though, even having a `<` could potentially be unsafe if the output was trimmed and concatenated with another user-controlled string. `<` should **always** be encoded as `&lt;`.

**Comment by ericnorris** [comment]
Additionally, I've examined the above fork and found two possible vulnerabilities that I have outlined here: https://github.com/megaplan/striptags/commit/9cc17473d22beef81ebc38e9ab15984bfa6f2e3c#commitcomment-28442164.

HTML safety and encoding can be tricky! This library takes a hard-line approach in order to ensure safety above all else. In cases where relaxed handling of malformed input may be desired, using an actual HTML parser or sanitizer may be a better fit.
