### ISSUE TITLE
Mangling Plaintext Due to False Tag Detection

### ISSUE THREAD

**Issue by stevenolay** [ericnorris/striptags#70]
Hello. 

I am doing the following. 

```
const text = 'All coffee is best served cold <3 https://www.gradyscoldbrew.com/'
const WHITELISTED_HTML_TAGS = ['a', 'img'];
const htmlTagsStripped = striptags(text, WHITELISTED_HTML_TAGS, ' ');
console.log(htmlTagsStripped)
```

My expected result is

```
'All coffee is best served cold <3 https://www.gradyscoldbrew.com/'
```

The actual result I am getting is

```
'All coffee is best served cold'
```

I think the <3 is tripping the parser up.

**Comment by ericnorris** [comment]
Hey @stevenolay! I believe this is doing the right thing - `<` is the start of a tag, and so technically `<3` is a tag named `3`. _Browsers_ might not necessarily treat this as a tag, but, if I understand correctly, it is. This library strips tags unapologetically, and is not meant to be a "smart" tag parser.

It's hard to tell exactly what you're doing, but from the context of your code snippet you're expecting `a` and `img` tags, and so it seems like you may be getting a string that isn't properly encoded - `<3` should actually be `&lt;3`. If you're not expecting this to have HTML, then you could instead HTML encode it, rather than trying to strip tags.

Either way, I'm going to close this issue. See https://github.com/ericnorris/striptags/issues/6, which is also closed, and references the same thing.

**Comment by stevenolay** [comment]
Hey @ericnorris ! Thanks for the followup.

So. I am using it to striptags for strings that may or may not be HTML. 

In my case text may be constructed from a plaintext editor or a rich text editor. And I use striptags as part of a preprocessing step. 

So the above example is one version of a string that may be passed to striptags. But strings in the following format may also be passed. 

```
const text = '<html>All coffee is best served cold &lt;3  <a href="https://www.gradyscoldbrew.com">Grady's Cold Brew</a> </html>'
const WHITELISTED_HTML_TAGS = ['a', 'img'];
const htmlTagsStripped = striptags(text, WHITELISTED_HTML_TAGS, ' ');
console.log(htmlTagsStripped)
```
