### ISSUE TITLE
Imports not work

### ISSUE THREAD

**Issue by KakakuCZ** [ericnorris/striptags#72]
Hello, I have problem with importing your library...

When I run
`const striptags = require("striptags")` - everything is fine.

But when Iam trying import with import keywork, it throws an error (striptag is undefined)
`import striptags from "striptags";`

When i want to use import keyword, I need to import by this way (despire my IDE whispering previous way):
`import * as striptags from "striptags";`.

Can you edit your library to allow importing by `import striptags from "striptags";`?

Context: Node 15, Nest.js
Thank you.

**Comment by MarcGodard** [comment]
I am having the same issue, however I feel this used to work as I found it in old code.

**Comment by ericnorris** [comment]
Hey @KakakuCZ,

As far as I can tell, `import`ing striptags works, so long as you follow the [README](https://github.com/ericnorris/striptags#examples):

```js
// notice that this is destructuring the result from "striptags"
import { striptags } from "striptags";

console.log(striptags);
console.log(striptags("hello world"));
```

...results in:

```
$ node main.js
[Function: striptags]
hello world
```

That said, I added a default export and the `exports` attribute to the `package.json` (thanks to #74) so that `import striptags from "striptags"` should now work as well. You can try it out with the latest `4.0.0-alpha.4` release.
