### ISSUE TITLE
Add exports property to package.json

### ISSUE THREAD

**Issue by typhonrt** [ericnorris/striptags#74]
Greets,

I'd like to find out if you can update `package.json` to support the `exports` field. I have made a fork of `striptags` that has this update and it works great. Also of course in the new release please do build it w/ rollup and publish the ESM and CJS distribution files vs `./src` 

Here are the changes necessary in package.json:

```
{
    "type": "module",
    "exports": {
        ".": {
            "types": "./dist/es6/striptags.d.ts",
            "import": "./dist/es6/striptags.js",
            "require": "./dist/cjs/striptags.js"
        },
        "./package.json": "./package.json"
    },
    "types": "./dist/es6/striptags.d.ts",
}
```

This also addresses #72. 

Thanks for your work on this useful utility package. I'm using my fork w/ the above successfully in a larger project pulling my fork directly from Github / not published on NPM, so I can verify that the above works. 

I also have some other brief code discussion aspects for consideration if you care to discuss, but I'll await your feedback on the above.

**Comment by ericnorris** [comment]
Thanks @typhonrt! It's disappointingly confusing to try to publish both a CJS and ES6-compatible library, and at the time I was following what seemed to be the _de facto_[^1] way of exposing the module via the `module` attribute in `package.json`.

I figured that adding a default export might be enough to solve #72, but it turns out that you're right and I must also add in the `exports` attribute. I've done so in `v4.0.0-alpha.4`, so let me know if that works for you.

Regarding other code suggestions, feel free to make a separate issue.

[^1]: https://stackoverflow.com/a/42817320, though the answer has been updated to include details about `exports` now.

**Comment by typhonrt** [comment]
Any chance you can do a release on NPM w/ the updated `exports` attribute? I am still using my fork because of this aspect. Also a note in the `exports` object for Typescript to work properly the `types` entry must be listed first. 

I did just see the [alpha release](https://www.npmjs.com/package/striptags/v/4.0.0-alpha.4), but perhaps it's good to release the mainline v4.
